-- Insert sample blog posts for TECH category
INSERT INTO blogs (title, content, category, subcategory, author, image_url, slug, featured, featured_in_category, popular, created_at) VALUES
('The Rise of AI in Everyday Technology', '<p>Exploring how artificial intelligence is becoming an integral part of our daily lives...</p>', 'TECH', 'News', 'Sarah Johnson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/ai-tech.webp', 'rise-of-ai-everyday-tech', true, true, true, NOW()),
('Best Budget Laptops Under ₹50,000', '<p>A comprehensive guide to the best value laptops in 2024...</p>', 'TECH', 'Tech Deals', 'Michael Chen', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/budget-laptops.webp', 'best-budget-laptops-2024', false, true, true, NOW() - INTERVAL '1 day'),
('5G Technology: The Future of Connectivity', '<p>Understanding the impact of 5G on future technologies...</p>', 'TECH', 'News', 'David Wilson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/5g-tech.webp', '5g-technology-future', false, true, false, NOW() - INTERVAL '2 days'),
('Amazon Great Indian Sale: Top Tech Deals', '<p>Best tech deals from Amazon''s latest sale event...</p>', 'TECH', 'Tech Deals', 'Priya Sharma', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/amazon-sale.webp', 'amazon-tech-deals-2024', true, false, true, NOW() - INTERVAL '3 days'),
('Quantum Computing Breakthrough', '<p>Latest developments in quantum computing technology...</p>', 'TECH', 'News', 'James Anderson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/quantum-computing.webp', 'quantum-computing-breakthrough', false, true, false, NOW() - INTERVAL '4 days'),
('Smart Home Gadgets Under ₹1000', '<p>Affordable smart home devices for every budget...</p>', 'TECH', 'Tech Deals', 'Lisa Chen', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/smart-home.webp', 'affordable-smart-home-gadgets', false, false, true, NOW() - INTERVAL '5 days'),
('The Evolution of Cloud Computing', '<p>How cloud technology has transformed business...</p>', 'TECH', 'News', 'Robert Miller', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/cloud-computing.webp', 'cloud-computing-evolution', true, false, false, NOW() - INTERVAL '6 days'),
('Best Smartphone Deals This Week', '<p>Top smartphone discounts and offers...</p>', 'TECH', 'Tech Deals', 'Amit Patel', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/phone-deals.webp', 'best-smartphone-deals', false, true, true, NOW() - INTERVAL '7 days'),
('Cybersecurity Trends 2024', '<p>Latest developments in cybersecurity...</p>', 'TECH', 'News', 'Emma Watson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/cybersecurity.webp', 'cybersecurity-trends-2024', false, false, true, NOW() - INTERVAL '8 days'),
('Tech Savings: Republic Day Sale', '<p>Best tech deals during Republic Day sales...</p>', 'TECH', 'Tech Deals', 'Rahul Kumar', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/republic-day-sale.webp', 'republic-day-tech-deals', true, true, false, NOW() - INTERVAL '9 days');

-- Insert sample blog posts for GAMES category
INSERT INTO blogs (title, content, category, subcategory, author, image_url, slug, featured, featured_in_category, popular, created_at) VALUES
('GTA 6 Release Date Announced', '<p>Everything we know about the upcoming GTA 6...</p>', 'GAMES', 'PS5', 'Alex Turner', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/gta6.webp', 'gta-6-release-date', true, true, true, NOW()),
('Xbox Game Pass February Games', '<p>New additions to Xbox Game Pass this month...</p>', 'GAMES', 'Xbox', 'Chris Roberts', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/xbox-gamepass-feb.webp', 'xbox-gamepass-february', false, true, true, NOW() - INTERVAL '1 day'),
('Nintendo Switch 2 Rumors', '<p>Latest leaks about Nintendo''s next console...</p>', 'GAMES', 'Nintendo', 'Maria Garcia', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/switch2.webp', 'nintendo-switch-2-rumors', true, false, true, NOW() - INTERVAL '2 days'),
('Best PC Games Under ₹500', '<p>Affordable PC games worth playing...</p>', 'GAMES', 'PC', 'Sam Wilson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/budget-pc-games.webp', 'best-budget-pc-games', false, true, false, NOW() - INTERVAL '3 days'),
('PS5 Pro: What to Expect', '<p>Analyzing rumors about the PS5 Pro...</p>', 'GAMES', 'PS5', 'Emily Brown', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/ps5-pro.webp', 'ps5-pro-expectations', true, true, false, NOW() - INTERVAL '4 days'),
('Xbox Series X vs PS5: 2024 Comparison', '<p>Updated comparison of the leading consoles...</p>', 'GAMES', 'Xbox', 'Daniel Lee', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/xbox-vs-ps5.webp', 'xbox-ps5-comparison-2024', false, false, true, NOW() - INTERVAL '5 days'),
('Zelda: BOTW 2 Review', '<p>Complete review of the latest Zelda game...</p>', 'GAMES', 'Nintendo', 'Sophie Martinez', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/zelda-botw2.webp', 'zelda-botw2-review', true, true, true, NOW() - INTERVAL '6 days'),
('Top PC Gaming Builds Under ₹50,000', '<p>Budget gaming PC build guide...</p>', 'GAMES', 'PC', 'Ryan Thompson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/budget-pc-build.webp', 'budget-gaming-pc-build', false, true, true, NOW() - INTERVAL '7 days'),
('PS5 Hidden Features Guide', '<p>Discovering lesser-known PS5 features...</p>', 'GAMES', 'PS5', 'Laura White', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/ps5-features.webp', 'ps5-hidden-features', false, false, true, NOW() - INTERVAL '8 days'),
('Xbox Game Studios: Upcoming Games', '<p>Preview of upcoming Xbox exclusives...</p>', 'GAMES', 'Xbox', 'Mike Johnson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/xbox-upcoming.webp', 'xbox-upcoming-games', true, true, false, NOW() - INTERVAL '9 days');

-- Insert sample blog posts for ENTERTAINMENT category
INSERT INTO blogs (title, content, category, subcategory, author, image_url, slug, featured, featured_in_category, popular, created_at) VALUES
('Deadpool 3: Everything We Know', '<p>Complete breakdown of Deadpool 3 details...</p>', 'ENTERTAINMENT', 'Movies', 'Rachel Kim', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/deadpool3.webp', 'deadpool-3-details', true, true, true, NOW()),
('The Last of Us Season 2 Cast', '<p>New cast members joining the HBO series...</p>', 'ENTERTAINMENT', 'Series', 'Tom Parker', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/tlou-s2.webp', 'last-of-us-season-2-cast', false, true, true, NOW() - INTERVAL '1 day'),
('Marvel Phase 5: Complete Guide', '<p>Upcoming Marvel movies and shows...</p>', 'ENTERTAINMENT', 'Movies', 'Jessica Lee', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/marvel-phase5.webp', 'marvel-phase-5-guide', true, false, true, NOW() - INTERVAL '2 days'),
('Best Netflix Series 2024', '<p>Must-watch Netflix shows this year...</p>', 'ENTERTAINMENT', 'Series', 'Mark Wilson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/netflix-2024.webp', 'best-netflix-series-2024', false, true, false, NOW() - INTERVAL '3 days'),
('DC Comics: Future Plans', '<p>DC''s upcoming comics and adaptations...</p>', 'ENTERTAINMENT', 'Comics', 'Peter Chang', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/dc-future.webp', 'dc-comics-future-plans', true, true, false, NOW() - INTERVAL '4 days'),
('Top 10 Movies of 2024 So Far', '<p>Best films released this year...</p>', 'ENTERTAINMENT', 'Movies', 'Sarah Adams', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/top-movies-2024.webp', 'top-movies-2024', false, false, true, NOW() - INTERVAL '5 days'),
('House of the Dragon Season 2', '<p>What to expect in the new season...</p>', 'ENTERTAINMENT', 'Series', 'John Smith', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/hotd-s2.webp', 'house-dragon-season-2', true, true, true, NOW() - INTERVAL '6 days'),
('Spider-Man Comics: New Arc', '<p>Latest developments in Spider-Man comics...</p>', 'ENTERTAINMENT', 'Comics', 'Mary Jane', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/spiderman-comics.webp', 'spiderman-comics-new-arc', false, true, true, NOW() - INTERVAL '7 days'),
('Oscar Nominations 2024', '<p>Complete list of Oscar nominees...</p>', 'ENTERTAINMENT', 'Movies', 'David Brown', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/oscars-2024.webp', 'oscar-nominations-2024', false, false, true, NOW() - INTERVAL '8 days'),
('Upcoming TV Shows 2024', '<p>Most anticipated series of 2024...</p>', 'ENTERTAINMENT', 'Series', 'Emma Davis', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/tv-shows-2024.webp', 'upcoming-tv-shows-2024', true, true, false, NOW() - INTERVAL '9 days');

-- Insert sample blog posts for STOCKS category
INSERT INTO blogs (title, content, category, subcategory, author, image_url, slug, featured, featured_in_category, popular, created_at) VALUES
('Bitcoin ETF Impact Analysis', '<p>How Bitcoin ETF approval affects crypto market...</p>', 'STOCKS', 'Crypto', 'Robert Chang', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/bitcoin-etf.webp', 'bitcoin-etf-analysis', true, true, true, NOW()),
('Nifty 50: Technical Analysis', '<p>Technical analysis of Nifty 50 index...</p>', 'STOCKS', 'Analysis', 'Vikram Mehta', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/nifty-analysis.webp', 'nifty-technical-analysis', false, true, true, NOW() - INTERVAL '1 day'),
('Upcoming IPOs in 2024', '<p>Major IPOs to watch this year...</p>', 'STOCKS', 'IPO', 'Neha Gupta', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/upcoming-ipos.webp', 'upcoming-ipos-2024', true, false, true, NOW() - INTERVAL '2 days'),
('Ethereum 2024 Price Prediction', '<p>Analysis of Ethereum''s future prospects...</p>', 'STOCKS', 'Crypto', 'Lisa Wong', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/ethereum-2024.webp', 'ethereum-price-prediction', false, true, false, NOW() - INTERVAL '3 days'),
('Bank Stocks: Sector Analysis', '<p>Comprehensive analysis of banking sector...</p>', 'STOCKS', 'Analysis', 'Rajesh Kumar', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/bank-stocks.webp', 'bank-stocks-analysis', true, true, false, NOW() - INTERVAL '4 days'),
('LIC IPO Performance Review', '<p>One year analysis of LIC stock...</p>', 'STOCKS', 'IPO', 'Sanjay Kapoor', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/lic-ipo.webp', 'lic-ipo-review', false, false, true, NOW() - INTERVAL '5 days'),
('Altcoin Investment Guide', '<p>Guide to investing in alternative cryptocurrencies...</p>', 'STOCKS', 'Crypto', 'Kevin Zhang', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/altcoin-guide.webp', 'altcoin-investment-guide', true, true, true, NOW() - INTERVAL '6 days'),
('Small Cap Stocks to Watch', '<p>Promising small cap stocks in 2024...</p>', 'STOCKS', 'Analysis', 'Priya Verma', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/small-cap.webp', 'small-cap-stocks-2024', false, true, true, NOW() - INTERVAL '7 days'),
('Crypto Market News Roundup', '<p>Weekly cryptocurrency market update...</p>', 'STOCKS', 'Crypto', 'Andrew Chen', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/crypto-news.webp', 'crypto-news-roundup', false, false, true, NOW() - INTERVAL '8 days'),
('IT Sector: Market Analysis', '<p>Analysis of IT sector stocks...</p>', 'STOCKS', 'Analysis', 'Deepak Sharma', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/it-stocks.webp', 'it-sector-analysis', true, true, false, NOW() - INTERVAL '9 days');

-- Insert sample blog posts for GADGETS category
INSERT INTO blogs (title, content, category, subcategory, author, image_url, slug, featured, featured_in_category, popular, created_at) VALUES
('iPhone 15 Pro Max Review', '<p>Comprehensive review of Apple''s flagship...</p>', 'GADGETS', 'MOBILE', 'James Wilson', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/iphone15-review.webp', 'iphone-15-pro-max-review', true, true, true, NOW()),
('MacBook Pro M3 Max Review', '<p>Testing Apple''s most powerful laptop...</p>', 'GADGETS', 'LAPTOPS', 'Thomas Lee', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/macbook-m3.webp', 'macbook-m3-max-review', false, true, true, NOW() - INTERVAL '1 day'),
('Samsung S24 Ultra First Look', '<p>Early impressions of Samsung''s flagship...</p>', 'GADGETS', 'MOBILE', 'Michelle Park', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/s24-ultra.webp', 'samsung-s24-ultra-first-look', true, false, true, NOW() - INTERVAL '2 days'),
('ROG Zephyrus G14 2024 Review', '<p>Review of the latest gaming laptop...</p>', 'GADGETS', 'LAPTOPS', 'Alex Chen', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/rog-g14.webp', 'rog-zephyrus-g14-review', false, true, false, NOW() - INTERVAL '3 days'),
('OnePlus 12 vs iPhone 15 Pro', '<p>Detailed comparison of flagship phones...</p>', 'GADGETS', 'MOBILE', 'Sarah Miller', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/oneplus-vs-iphone.webp', 'oneplus12-iphone15-comparison', true, true, false, NOW() - INTERVAL '4 days'),
('Dell XPS 13 Plus Review', '<p>Review of Dell''s premium ultrabook...</p>', 'GADGETS', 'LAPTOPS', 'Richard Brown', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/xps-13.webp', 'dell-xps-13-plus-review', false, false, true, NOW() - INTERVAL '5 days'),
('Nothing Phone 2 Long-term Review', '<p>After 6 months with Nothing Phone 2...</p>', 'GADGETS', 'MOBILE', 'Jennifer Lee', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/nothing-phone2.webp', 'nothing-phone-2-review', true, true, true, NOW() - INTERVAL '6 days'),
('Lenovo Legion Pro 7i Review', '<p>Testing Lenovo''s gaming powerhouse...</p>', 'GADGETS', 'LAPTOPS', 'Michael Scott', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/legion-pro7i.webp', 'lenovo-legion-pro-review', false, true, true, NOW() - INTERVAL '7 days'),
('Pixel 8 Pro Camera Test', '<p>In-depth camera analysis of Pixel 8 Pro...</p>', 'GADGETS', 'MOBILE', 'Emma White', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/pixel8-camera.webp', 'pixel-8-pro-camera-test', false, false, true, NOW() - INTERVAL '8 days'),
('MacBook Air M3 vs Windows Laptops', '<p>Comparing MacBook Air with competitors...</p>', 'GADGETS', 'LAPTOPS', 'David Clark', 'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/macbook-vs-windows.webp', 'macbook-air-comparison', true, true, false, NOW() - INTERVAL '9 days');