-- Insert additional mobile products
INSERT INTO mobile_products (
  name,
  brand,
  price,
  display_specs,
  processor,
  ram,
  storage,
  battery,
  camera,
  chipset,
  charging_specs,
  resolution,
  screen_size,
  color,
  os,
  image_url,
  announced,
  status,
  display_type,
  display_protection,
  dimensions,
  weight,
  build_material,
  sim_type,
  wlan,
  bluetooth,
  nfc,
  gps,
  usb_type,
  network_technology,
  network_speed,
  loudspeaker_type,
  audio_jack,
  sensors,
  available_colors,
  bands_2g,
  bands_3g,
  bands_4g,
  bands_5g
) VALUES
-- Xiaomi 14 Pro
(
  'Xiaomi 14 Pro',
  'Xiaomi',
  69999.00,
  'LTPO AMOLED, 120Hz, Dolby Vision, HDR10+',
  'Snapdragon 8 Gen 3',
  '12GB',
  '512GB',
  '4880 mAh',
  '50MP + 50MP + 50MP',
  'Snapdragon 8 Gen 3',
  '120W HyperCharge',
  '1440 x 3200 pixels',
  '6.73 inches',
  'Titanium Black',
  'Android 14, HyperOS',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/xiaomi14pro.webp',
  'December 2023',
  'Available',
  'LTPO AMOLED',
  'Gorilla Glass Victus 2',
  '161.4 x 75.3 x 8.5 mm',
  '223 g',
  'Glass front, titanium frame, ceramic back',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 7',
  '5.4',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS, NavIC',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers, tuned by Harman Kardon',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass', 'color spectrum'],
  ARRAY['Titanium Black', 'Titanium White', 'Titanium Green'],
  ARRAY['GSM 850', 'GSM 900', 'GSM 1800', 'GSM 1900'],
  ARRAY['HSDPA 800', 'HSDPA 850', 'HSDPA 900', 'HSDPA 1700', 'HSDPA 1900', 'HSDPA 2100'],
  ARRAY['LTE 1', 'LTE 2', 'LTE 3', 'LTE 4', 'LTE 5', 'LTE 7', 'LTE 8', 'LTE 20', 'LTE 28', 'LTE 38', 'LTE 40', 'LTE 41'],
  ARRAY['5G NR 1', '5G NR 3', '5G NR 5', '5G NR 7', '5G NR 8', '5G NR 20', '5G NR 28', '5G NR 38', '5G NR 41', '5G NR 77', '5G NR 78']
);

-- Insert remaining products
INSERT INTO mobile_products (
  name,
  brand,
  price,
  display_specs,
  processor,
  ram,
  storage,
  battery,
  camera,
  chipset,
  charging_specs,
  resolution,
  screen_size,
  color,
  os,
  image_url,
  announced,
  status,
  display_type,
  display_protection,
  dimensions,
  weight,
  build_material,
  sim_type,
  wlan,
  bluetooth,
  nfc,
  gps,
  usb_type,
  network_technology,
  network_speed,
  loudspeaker_type,
  audio_jack,
  sensors,
  available_colors
) VALUES
-- Google Pixel 8 Pro
(
  'Pixel 8 Pro',
  'Google',
  106999.00,
  'LTPO OLED, 120Hz, HDR10+',
  'Google Tensor G3',
  '12GB',
  '256GB',
  '5050 mAh',
  '50MP + 48MP + 48MP',
  'Google Tensor G3',
  '30W Fast Charging',
  '1344 x 2992 pixels',
  '6.7 inches',
  'Bay Blue',
  'Android 14',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/pixel8pro.webp',
  'October 2023',
  'Available',
  'LTPO OLED',
  'Gorilla Glass Victus 2',
  '162.6 x 76.5 x 8.8 mm',
  '213 g',
  'Glass front (Gorilla Glass Victus 2), glass back, aluminum frame',
  'Nano-SIM and eSIM',
  'Wi-Fi 7',
  '5.3',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass', 'barometer'],
  ARRAY['Bay Blue', 'Porcelain', 'Obsidian']
);