-- Insert additional mobile products
INSERT INTO mobile_products (
  name,
  brand,
  price,
  display_specs,
  processor,
  ram,
  storage,
  battery,
  camera,
  chipset,
  charging_specs,
  resolution,
  screen_size,
  color,
  os,
  image_url,
  announced,
  status,
  display_type,
  display_protection,
  dimensions,
  weight,
  build_material,
  sim_type,
  wlan,
  bluetooth,
  nfc,
  gps,
  usb_type,
  network_technology,
  network_speed,
  loudspeaker_type,
  audio_jack,
  sensors,
  available_colors
) VALUES
-- Xiaomi 14 Pro
(
  'Xiaomi 14 Pro',
  'Xiaomi',
  69999.00,
  'LTPO AMOLED, 120Hz, Dolby Vision, HDR10+',
  'Snapdragon 8 Gen 3',
  '12GB',
  '512GB',
  '4880 mAh',
  '50MP + 50MP + 50MP',
  'Snapdragon 8 Gen 3',
  '120W HyperCharge',
  '1440 x 3200 pixels',
  '6.73 inches',
  'Titanium Black',
  'Android 14, HyperOS',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/xiaomi14pro.webp',
  'December 2023',
  'Available',
  'LTPO AMOLED',
  'Gorilla Glass Victus 2',
  '161.4 x 75.3 x 8.5 mm',
  '223 g',
  'Glass front, titanium frame, ceramic back',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 7',
  '5.4',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS, NavIC',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers, tuned by Harman Kardon',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass', 'color spectrum'],
  ARRAY['Titanium Black', 'Titanium White', 'Titanium Green']
),

-- Google Pixel 8 Pro
(
  'Pixel 8 Pro',
  'Google',
  106999.00,
  'LTPO OLED, 120Hz, HDR10+',
  'Google Tensor G3',
  '12GB',
  '256GB',
  '5050 mAh',
  '50MP + 48MP + 48MP',
  'Google Tensor G3',
  '30W Fast Charging',
  '1344 x 2992 pixels',
  '6.7 inches',
  'Bay Blue',
  'Android 14',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/pixel8pro.webp',
  'October 2023',
  'Available',
  'LTPO OLED',
  'Gorilla Glass Victus 2',
  '162.6 x 76.5 x 8.8 mm',
  '213 g',
  'Glass front (Gorilla Glass Victus 2), glass back, aluminum frame',
  'Nano-SIM and eSIM',
  'Wi-Fi 7',
  '5.3',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass', 'barometer'],
  ARRAY['Bay Blue', 'Porcelain', 'Obsidian']
),

-- Vivo X100 Pro
(
  'Vivo X100 Pro',
  'Vivo',
  89999.00,
  'LTPO AMOLED, 120Hz, HDR10+',
  'Dimensity 9300',
  '16GB',
  '512GB',
  '5400 mAh',
  '50MP + 50MP + 50MP',
  'Dimensity 9300',
  '100W FlashCharge',
  '1260 x 2800 pixels',
  '6.78 inches',
  'Asteroid Black',
  'Android 14, Funtouch OS 14',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/vivox100pro.webp',
  'November 2023',
  'Available',
  'LTPO AMOLED',
  'Gorilla Glass Victus',
  '164.1 x 75.3 x 8.9 mm',
  '225 g',
  'Glass front, glass back, aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 7',
  '5.4',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS, NavIC',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass'],
  ARRAY['Asteroid Black', 'Startrail Blue']
),

-- OPPO Find X7 Ultra
(
  'OPPO Find X7 Ultra',
  'OPPO',
  84999.00,
  'LTPO AMOLED, 120Hz, HDR10+',
  'Snapdragon 8 Gen 3',
  '16GB',
  '512GB',
  '5000 mAh',
  '50MP + 50MP + 50MP + 50MP',
  'Snapdragon 8 Gen 3',
  '100W SuperVOOC',
  '1440 x 3168 pixels',
  '6.82 inches',
  'Ocean Blue',
  'Android 14, ColorOS 14',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/findx7ultra.webp',
  'January 2024',
  'Available',
  'LTPO AMOLED',
  'Gorilla Glass Victus 2',
  '164.3 x 76.2 x 9.1 mm',
  '221 g',
  'Glass front, eco leather back, aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 7',
  '5.4',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass'],
  ARRAY['Ocean Blue', 'Desert Silver', 'Vast Black']
),

-- iQOO 12
(
  'iQOO 12',
  'iQOO',
  52999.00,
  'LTPO AMOLED, 144Hz, HDR10+',
  'Snapdragon 8 Gen 3',
  '12GB',
  '256GB',
  '5000 mAh',
  '50MP + 50MP + 64MP',
  'Snapdragon 8 Gen 3',
  '120W FlashCharge',
  '1260 x 2800 pixels',
  '6.78 inches',
  'Legend White',
  'Android 14, Funtouch OS 14',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/iqoo12.webp',
  'December 2023',
  'Available',
  'LTPO AMOLED',
  'Gorilla Glass Victus',
  '163.2 x 75.9 x 8.1 mm',
  '204 g',
  'Glass front, glass back, aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 7',
  '5.3',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass'],
  ARRAY['Legend White', 'Carbon Black']
);

-- Insert remaining 5 products
INSERT INTO mobile_products (
  name,
  brand,
  price,
  display_specs,
  processor,
  ram,
  storage,
  battery,
  camera,
  chipset,
  charging_specs,
  resolution,
  screen_size,
  color,
  os,
  image_url,
  announced,
  status,
  display_type,
  display_protection,
  dimensions,
  weight,
  build_material,
  sim_type,
  wlan,
  bluetooth,
  nfc,
  gps,
  usb_type,
  network_technology,
  network_speed,
  loudspeaker_type,
  audio_jack,
  sensors,
  available_colors
) VALUES
-- Realme GT5 Pro
(
  'Realme GT5 Pro',
  'Realme',
  44999.00,
  'AMOLED, 144Hz, HDR10+',
  'Snapdragon 8 Gen 3',
  '12GB',
  '256GB',
  '5400 mAh',
  '50MP + 8MP + 50MP',
  'Snapdragon 8 Gen 3',
  '100W SuperVOOC',
  '1240 x 2772 pixels',
  '6.78 inches',
  'Red Rock',
  'Android 14, Realme UI 5.0',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/gt5pro.webp',
  'December 2023',
  'Available',
  'AMOLED',
  'Gorilla Glass Victus',
  '161.7 x 75.1 x 9.2 mm',
  '218 g',
  'Glass front, glass back, aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 7',
  '5.3',
  true,
  'GPS, GLONASS, BDS, GALILEO',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass'],
  ARRAY['Red Rock', 'Bright Night']
),

-- Motorola Edge 40 Pro
(
  'Motorola Edge 40 Pro',
  'Motorola',
  54999.00,
  'P-OLED, 165Hz, HDR10+',
  'Snapdragon 8 Gen 2',
  '12GB',
  '256GB',
  '4600 mAh',
  '50MP + 50MP + 12MP',
  'Snapdragon 8 Gen 2',
  '125W TurboPower',
  '1080 x 2400 pixels',
  '6.67 inches',
  'Interstellar Black',
  'Android 13',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/edge40pro.webp',
  'April 2023',
  'Available',
  'P-OLED',
  'Gorilla Glass Victus',
  '161.2 x 74 x 8.6 mm',
  '199 g',
  'Glass front (Gorilla Glass Victus), glass back, aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 6E',
  '5.3',
  true,
  'GPS, GLONASS, BDS, GALILEO',
  'USB Type-C 3.1',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  false,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass'],
  ARRAY['Interstellar Black', 'Lunar Blue']
),

-- ASUS ROG Phone 7 Ultimate
(
  'ASUS ROG Phone 7 Ultimate',
  'ASUS',
  99999.00,
  'AMOLED, 165Hz, HDR10+',
  'Snapdragon 8 Gen 2',
  '16GB',
  '512GB',
  '6000 mAh',
  '50MP + 13MP + 8MP',
  'Snapdragon 8 Gen 2',
  '65W HyperCharge',
  '1080 x 2448 pixels',
  '6.78 inches',
  'Storm White',
  'Android 13, ROG UI',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/rogphone7.webp',
  'April 2023',
  'Available',
  'AMOLED',
  'Gorilla Glass Victus',
  '173 x 77 x 10.3 mm',
  '239 g',
  'Glass front (Gorilla Glass Victus), glass back, aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 7',
  '5.3',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS, NavIC',
  'USB Type-C 3.1',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers with Dirac HD Sound',
  true,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass', 'color spectrum'],
  ARRAY['Storm White']
),

-- Sony Xperia 1 V
(
  'Sony Xperia 1 V',
  'Sony',
  129999.00,
  '4K HDR OLED, 120Hz',
  'Snapdragon 8 Gen 2',
  '12GB',
  '256GB',
  '5000 mAh',
  '48MP + 12MP + 12MP',
  'Snapdragon 8 Gen 2',
  '30W Fast Charging',
  '1644 x 3840 pixels',
  '6.5 inches',
  'Black',
  'Android 13',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/xperia1v.webp',
  'May 2023',
  'Available',
  '4K HDR OLED',
  'Gorilla Glass Victus 2',
  '165 x 71 x 8.3 mm',
  '187 g',
  'Glass front (Gorilla Glass Victus 2), glass back, aluminum frame',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 6E',
  '5.3',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS',
  'USB Type-C 3.2',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  true,
  ARRAY['Fingerprint (side-mounted)', 'accelerometer', 'gyro', 'proximity', 'compass', 'color spectrum'],
  ARRAY['Black', 'Khaki Green']
),

-- Redmi Note 13 Pro+
(
  'Redmi Note 13 Pro+',
  'Redmi',
  31999.00,
  'AMOLED, 120Hz, HDR10+',
  'Dimensity 7200 Ultra',
  '12GB',
  '256GB',
  '5000 mAh',
  '200MP + 8MP + 2MP',
  'Dimensity 7200 Ultra',
  '120W HyperCharge',
  '1220 x 2712 pixels',
  '6.67 inches',
  'Midnight Black',
  'Android 13, MIUI 14',
  'https://fkthvcaehstlbkgztspt.supabase.co/storage/v1/object/public/blog-images/note13proplus.webp',
  'January 2024',
  'Available',
  'AMOLED',
  'Gorilla Glass Victus',
  '161.4 x 74.2 x 8.9 mm',
  '204 g',
  'Glass front (Gorilla Glass Victus), glass back',
  'Dual SIM (Nano-SIM, dual stand-by)',
  'Wi-Fi 6',
  '5.2',
  true,
  'GPS, GLONASS, BDS, GALILEO, QZSS',
  'USB Type-C 2.0',
  'GSM / HSPA / LTE / 5G',
  'HSPA, LTE-A, 5G',
  'Stereo speakers',
  true,
  ARRAY['Fingerprint (under display, optical)', 'accelerometer', 'gyro', 'proximity', 'compass'],
  ARRAY['Midnight Black', 'Purple', 'White']
);